version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

metrics:
  address: 0.0.0.0:2112

server:
  command: 'php app.php'
  relay: pipes
  env:
    - MODE: roadrunner
  on_init:
    command: "php app.php configure"

logs:
  level: ${RR_LOG_LEVEL:-info}

http:
  address: 127.0.0.1:8082
  middleware: [ "headers" ]
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
  pool:
    num_workers: ${RR_HTTP_NUM_WORKERS}

tcp:
  servers:
    monolog:
      addr: :9913
      delimiter: "\n"
    var-dumper:
      addr: :9912
      delimiter: "\n"
    smtp:
      addr: :1025
  pool:
    num_workers: ${RR_TCP_NUM_WORKERS}

kv:
  events:
    driver: memory
    config: { }
  local:
    driver: memory
    config: { }

jobs:
  consume: [ ]

service:
  nginx:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 1
    command: "/usr/sbin/nginx"
  centrifuge:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 1
    command: "./bin/centrifugo --config=centrifugo.json"

centrifuge:
  proxy_address: ${RR_CENTRIFUGE_PROXY_ADDRESS}
  grpc_api_address: ${RR_CENTRIFUGE_GRPC_API_ADDRESS}
  poll:
    num_workers: ${RR_CENTRIFUGE_NUM_WORKERS}
