on:
  pull_request: null

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      install_protoc: true
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.2', '8.3']
      stability: >-
        ['prefer-stable']
