on:
  pull_request: null

name: phpunit

jobs:
  phpunit-db:
    uses: buggregator/gh-actions/.github/workflows/phpunit.yml@master
    with:
      extensions: >-
        ['sockets', 'mongodb', 'pgsql', 'pdo_pgsql', 'pdo_mysql']
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.3']
      stability: >-
        ['prefer-stable']
    env:
      PERSISTENCE_DRIVER: db
      DB_DRIVER: sqlite

  phpunit-memory:
    uses: buggregator/gh-actions/.github/workflows/phpunit.yml@master
    with:
      extensions: >-
        ['sockets', 'mongodb', 'pgsql', 'pdo_pgsql', 'pdo_mysql']
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.3']
      stability: >-
        ['prefer-stable']
    env:
      PERSISTENCE_DRIVER: memory
